### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by LightAMV** [imoutits/PokeIV#13]
Title^ When renaming a pokemon.

**Comment by Nurah123** [comment]
Similar issue, I loaded using the  pokeIV-gui.exe with windows 10. 
Steps Taken
I clicked the sort by nickname feature and selected all pokemon with no nickname and then clicked Rename button.
It gave me this error log:

Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1537, in **call**
  File "pokeivwindow.pyc", line 192, in set_config
  File "pokeivwindow.pyc", line 154, in reset_windows
  File "pokeivwindow.pyc", line 339, in reset_tree_window
  File "pokeivwindow.pyc", line 432, in get_info
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1537, in **call**
  File "pokeivwindow.pyc", line 491, in rename_action
  File "pokeivwindow.pyc", line 154, in reset_windows
  File "pokeivwindow.pyc", line 339, in reset_tree_window
  File "pokeivwindow.pyc", line 432, in get_info
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)

**Comment by canele** [comment]
Hmm. I assume it's nidoran that's breaking it (the unicode in error for both of you is ♂)?  I'm not sure why that's being assigned since none of the code or resources are using that symbol. I unfortunately can't test  it since I haven't seen that error, but I've pushed a hopeful fix. Let me know if it works now.
