### ISSUE TITLE
Unable to run Windows version on Windows 10

### ISSUE THREAD

**Issue by voidstar-x** [imoutits/PokeIV#15]
Error occured when running the Windows executable on Windows 10. Log details:

Traceback (most recent call last):
  File "pokeIV-gui.py", line 176, in <module>
    main()
  File "pokeIV-gui.py", line 126, in main
    start(config)
  File "pokeIV-gui.py", line 141, in start
    with open('german-names.tsv') as f:
IOError: [Errno 2] No such file or directory: 'german-names.tsv'

**Comment by canele** [comment]
My bad, it should work now.
