### ISSUE TITLE
CLI version throws errors

### ISSUE THREAD

**Issue by PascalTemel** [imoutits/PokeIV#3]
```
Traceback (most recent call last):
  File "pokeIV.py", line 249, in <module>
    main()
  File "pokeIV.py", line 240, in main
    print_evolve_candidates(data)
  File "pokeIV.py", line 152, in print_evolve_candidates
    print('{0:<10} {1:^15} {2:^17} {3:^10}'.format(data["pokedex"][id],data["evolve_counts"][id],data["unique_counts"][id],""))
KeyError: '60'
```

Tried a fresh install and it didn't work either. Ubuntu 16.04

**Comment by canele** [comment]
That should be fixed now.
